### ISSUE TITLE
Nicks not right-aligned; nick not displayed

### ISSUE THREAD

**Issue by StylinGreymon** [ronilaukkarinen/weed#13]
Using your theme, and everything seems to work except nicks aren't aligning to the right, which makes things look a lot more chaotic, and my own nick isn't being displayed at all.

I guess an image would be easier to see:
![irssi woes](https://cloud.githubusercontent.com/assets/5328232/10708517/23ea1db8-79c0-11e5-93f4-82f2a65ff879.png)

**Comment by StylinGreymon** [comment]
Apologies, I had mistyped a few things when editing the theme.

**Comment by vonpupp** [comment]
I'm having the same problem here, how did you solve it @StylinGreymon ?

Thanks.

**Comment by StylinGreymon** [comment]
I don't quite remember which line I messed up on in the weed.theme, but it
was one of these lines under formats = {:

    own_msg = "{ownmsgnick $2 {ownnick $[-10]0}}%W$1";
    own_msg_channel = "{ownmsgnick $3 {ownnick $[-10]0}{msgchannel
$1}}%w%_$2";
    pubmsg_me = "{pubmsgmenick $2 {menick $[-10]0}}%_$1";
    pubmsg_me_channel = "{pubmsgmenick $3 {menick $[-10]0}{msgchannel
$1}}$2";
    pubmsg_hilight = "{pubmsghinick $0 $3 $[-10]1}$2";
    pubmsg_hilight_channel = "{pubmsghinick $0 $4 $[-10]1{msgchannel
$2}}$3";
    pubmsg = "{pubmsgnick $2 {pubnick $nickcolor$[-10]0}}$1";
    pubmsg_channel = "{pubmsgnick $3 {pubnick $[-10]0}{msgchannel $1}}$2";

That should clear it up.

**Comment by vonpupp** [comment]
Thanks a lot!

Aparently I have to comment [these lines] and [uncoment these]. So far so good, however, I still need to further test if everything is ok. It has been a while since I don't use irssi.

Regards!

[these lines]: https://github.com/ronilaukkarinen/weed/blob/acade19c60d248b846ec28a80dbb97666cae5d1b/weed.theme#L202-L203
[uncoment these]: https://github.com/ronilaukkarinen/weed/blob/acade19c60d248b846ec28a80dbb97666cae5d1b/weed.theme#L211-L212
