### ISSUE TITLE
Can't get nickcolor.pl to work

### ISSUE THREAD

**Issue by fayad** [ronilaukkarinen/weed#15]
I tried to get nickcolor.pl to work as per the steps given. I am using screen for irssi (v 0.8.17)

/script load nickcolor_expando is the step under https://github.com/ronilaukkarinen/weed#each-nick-in-different-colors but script is called nickcolor.pl. Did we miss something here ?

I tried running it with "/set nickcolor_colors rRyYbBmMcC" as in the perl script comments and it would show as value assigned. But colors for nicklist doesn't change. $TERM inside screen is screen-256color.

**Comment by fayad** [comment]
I guess this is the answer to my issue. https://github.com/ronilaukkarinen/weed/issues/9.

**Comment by ronilaukkarinen** [comment]
I admit that part is a bit incomplete since we are going through an enhancement and it's not yet ready. I haven't implemented nickcolor_expando correctly yet with the repo, so it's not implemented. I should have mentioned that, so let's leave this issue open for now.

I have `neat_colors` set as `X30rRX61X6CX3CyX1DcCBX3HX2AbMX3AX42X6M`. Please try `/set neat_colors X30rRX61X6CX3CyX1DcCBX3HX2AbMX3AX42X6M`. It has the correct colors currently for this theme.

Sorry for the inconvenience.

**Comment by fayad** [comment]
No problem. Thanks for clearing that.

I loaded the script and /set the value. No errors reported but I cannot get the nick colors yet. There is something I am missing. $TERM is xterm-256color on shell and screen-256color on screen. mirc_blink_fix is off.

**Comment by mitral** [comment]
Does it work now? The script?

**Comment by ronilaukkarinen** [comment]
Closing due inactivity.
