### ISSUE TITLE
OP status etc

### ISSUE THREAD

**Issue by xorb0ss** [ronilaukkarinen/weed#7]
Hi there,

Just wondering how I can make the theme, which is awesome by the way, display the little symbols related with OP, voice etc (@, +) as I'm unable to distinguish who is who currently.

Cheers.

**Comment by ronilaukkarinen** [comment]
Thanks! This is really a matter of taste. I left them out also because with them the long nicknames are even shorter and with nicklist irssi script you can see the ops on top in the list on the right side of the window (just like in Xchat, which was the inspiration of this theme). For me it doesn't really matter who is the op, but I can see them with nicklist or `/names`.

If you want to add operator to the theme file yourself, you can add `$1` just before `$1` to all the `msgnick` parts. My older theme [envy](https://github.com/ronilaukkarinen/envy/blob/master/envy.theme) has the operator statuses so you can take a look how it's done.

If more people need the op status in this theme, I'll add them, but for now I'll leave as it is.
